using System.Text;
using Microsoft.CodeAnalysis;

namespace H3.Data;

[Generator]
public class BaseCellsGenerator : IIncrementalGenerator {

    private static readonly string _indent = string.Empty.PadLeft(12, ' ');

    private const string Template = @"// <auto-generated/>

namespace H3.Model;

/// <summary>
/// All of the 122 base cells that comprise the H3 indexing scheme.
/// </summary>
public static partial class BaseCells {{

    private static readonly sbyte[] NotAPentagonOffsets = {{ 0, 0 }};

    /// <summary>
    /// The neighbouring base cell for each base cell in each of the 7
    /// directions, flattened as [cell * 7 + direction].  A value of 127
    /// (<see cref=""LookupTables.INVALID_BASE_CELL""/>) indicates the deleted
    /// k-axes direction of a pentagon.
    /// </summary>
    internal static readonly sbyte[] NeighbouringCells = {{
{1}
    }};

    /// <summary>
    /// The number of 60 degree ccw rotations required to rotate into the
    /// orientation of the neighbouring base cell for each base cell in each
    /// of the 7 directions, flattened as [cell * 7 + direction].
    /// </summary>
    internal static readonly sbyte[] NeighbourCounterClockwiseRotations = {{
{2}
    }};

    /// <summary>
    /// Bitmask of the pentagon base cells 0 - 63.
    /// </summary>
    internal const ulong PentagonMask0 = 0x{3:X}UL;

    /// <summary>
    /// Bitmask of the pentagon base cells 64 - 121, offset by -64.
    /// </summary>
    internal const ulong PentagonMask1 = 0x{4:X}UL;
{0}
    public static readonly BaseCell[] Cells = {{
{5}
    }};

}}
";

    public void Initialize(IncrementalGeneratorInitializationContext context) =>
        context.RegisterPostInitializationOutput(Execute);

    private static void Execute(IncrementalGeneratorPostInitializationContext context) {
        var cells = new StringBuilder();
        var cellNames = new StringBuilder();
        var neighbours = new StringBuilder();
        var neighbourRotations = new StringBuilder();
        var pentagonMask0 = 0UL;
        var pentagonMask1 = 0UL;

        for (var c = 0; c < Constants.NUM_BASE_CELLS; c += 1) {
            var cell = LookupTables.BaseCells[c];
            cellNames.Append($"{_indent}BaseCell{c}{(c < 121 ? ",\n" : "")}");

            var neighbourRow = new StringBuilder();
            var rotationRow = new StringBuilder();
            for (var d = 0; d < 7; d += 1) {
                neighbourRow.Append($"{LookupTables.Neighbours[c, d]}, ");
                rotationRow.Append($"{LookupTables.NeighbourCounterClockwiseRotations[c, d]}, ");
            }

            neighbours.Append($"        {neighbourRow}// base cell {c}{(c < 121 ? "\n" : "")}");
            neighbourRotations.Append($"        {rotationRow}// base cell {c}{(c < 121 ? "\n" : "")}");

            if (cell.IsPentagon) {
                if (c < 64) {
                    pentagonMask0 |= 1UL << c;
                } else {
                    pentagonMask1 |= 1UL << (c - 64);
                }
            }

            cells.Append($@"
        private static readonly BaseCell BaseCell{c} = new() {{
            Cell = {c},
            Home = new FaceIJK {{
                Face = {cell.Home.Face},
                Coord = new CoordIJK {{ I = {cell.Home.I}, J = {cell.Home.J}, K = {cell.Home.K} }}
            }},
            IsPentagon = {(cell.IsPentagon ? "true" : "false")},
            IsPolarPentagon = {(c == 4 || c == 117 ? "true" : "false")},
            ClockwiseOffsetPent = {(cell.IsPentagon ? $"new sbyte[] {{ {cell.ClockwiseOffsetPent[0]}, {cell.ClockwiseOffsetPent[1]} }}" : "NotAPentagonOffsets")}
        }};
");
        }

        context.AddSource("BaseCells.g.cs", string.Format(
            Template, cells, neighbours, neighbourRotations, pentagonMask0, pentagonMask1, cellNames));
    }

}
