using System.Text;
using Microsoft.CodeAnalysis;

namespace H3.Data;

[Generator]
public class LookupTablesGenerator : IIncrementalGenerator {

    private const string Template = @"// <auto-generated/>

namespace H3.Model;

public static partial class LookupTables {{

    /// <summary>
    /// Resolution 0 base cell lookup table for each face, flattened as
    /// [face * 27 + i * 9 + j * 3 + k].  Provides the base cell located at
    /// the given resolution 0 ijk+ coordinate (0 &lt;= i, j, k &lt;= 2) in
    /// the face's face-centered ijk coordinate system.
    /// </summary>
    internal static readonly byte[] FaceIjkBaseCellTable = {{
{0}
    }};

    /// <summary>
    /// Number of 60 degree ccw rotations required to rotate into the
    /// orientation of the base cell given by <see cref=""FaceIjkBaseCellTable""/>,
    /// flattened as [face * 27 + i * 9 + j * 3 + k].
    /// </summary>
    internal static readonly byte[] FaceIjkBaseCellRotationTable = {{
{1}
    }};

    /// <summary>
    /// Traversal table for class II grids, indexed as
    /// [currentDigit * 7 + direction].  The low 3 bits contain the new
    /// digit and the next 3 bits contain the new ap7 move to perform at
    /// the coarser resolution.
    /// </summary>
    internal static readonly byte[] TraversalPackedClass2 = {{
{2}
    }};

    /// <summary>
    /// Traversal table for class III grids, indexed as
    /// [currentDigit * 7 + direction].  The low 3 bits contain the new
    /// digit and the next 3 bits contain the new ap7 move to perform at
    /// the coarser resolution.
    /// </summary>
    internal static readonly byte[] TraversalPackedClass3 = {{
{3}
    }};

    /// <summary>
    /// All cell indexes that are pentagons, per resolution.
    /// </summary>
    public static readonly H3.H3Index[][] PentagonIndexesPerResolution = {{
{4}
    }};

}}
";

    public void Initialize(IncrementalGeneratorInitializationContext context) =>
        context.RegisterPostInitializationOutput(Execute);

    private static void Execute(IncrementalGeneratorPostInitializationContext context) {
        var faceIjkCells = new StringBuilder();
        var faceIjkRotations = new StringBuilder();

        for (var face = 0; face < Constants.NUM_ICOSA_FACES; face += 1) {
            var cellRow = new StringBuilder();
            var rotationRow = new StringBuilder();

            for (var i = 0; i < 3; i += 1) {
                for (var j = 0; j < 3; j += 1) {
                    for (var k = 0; k < 3; k += 1) {
                        var entry = LookupTables.FaceIjkBaseCells[face, i, j, k];
                        cellRow.Append($"{entry.Cell}, ");
                        rotationRow.Append($"{entry.CounterClockwiseRotations}, ");
                    }
                }
            }

            faceIjkCells.Append($"        {cellRow}// face {face}{(face < 19 ? "\n" : "")}");
            faceIjkRotations.Append($"        {rotationRow}// face {face}{(face < 19 ? "\n" : "")}");
        }

        var packedClass2 = BuildPackedTraversal(LookupTables.NewDirectionClass2, LookupTables.NewAdjustmentClass2);
        var packedClass3 = BuildPackedTraversal(LookupTables.NewDirectionClass3, LookupTables.NewAdjustmentClass3);

        var pentagons = new StringBuilder();
        for (var resolution = 0; resolution <= Constants.MAX_H3_RES; resolution += 1) {
            var row = new StringBuilder();
            for (var c = 0; c < Constants.NUM_BASE_CELLS; c += 1) {
                if (!LookupTables.BaseCells[c].IsPentagon) continue;

                // mode Cell, resolution, base cell, digits 1..res centered and
                // the remainder invalid
                var value = (1UL << 59) |
                            ((ulong)resolution << 52) |
                            ((ulong)c << 45) |
                            ((1UL << ((Constants.MAX_H3_RES - resolution) * 3)) - 1);
                row.Append($"new(0x{value:X}UL), ");
            }

            pentagons.Append($"        new H3.H3Index[] {{ {row}}},{(resolution < Constants.MAX_H3_RES ? "\n" : "")}");
        }

        context.AddSource("LookupTables.g.cs", string.Format(
            Template, faceIjkCells, faceIjkRotations, packedClass2, packedClass3, pentagons));
    }

    private static string BuildPackedTraversal(Direction[,] newDirection, Direction[,] newAdjustment) {
        var builder = new StringBuilder();

        for (var digit = 0; digit < 7; digit += 1) {
            var row = new StringBuilder();
            for (var direction = 0; direction < 7; direction += 1) {
                var packed = (int)newDirection[digit, direction] | ((int)newAdjustment[digit, direction] << 3);
                row.Append($"{packed}, ");
            }

            builder.Append($"        {row}// digit {digit}{(digit < 6 ? "\n" : "")}");
        }

        return builder.ToString();
    }

}
